### ISSUE TITLE
Test that the `exemplar.json` GeometryCollection is parsed correctly

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-topojson#17]
Currently we don't actually test if the parsing of the TopoJSON document is correct with respect to the inner GeometryCollection i.e. the values:

```json 
{
    "type": "Point",
    "properties": {
      "prop0": "value0"
    },
    "coordinates": [102, 0.5]
  },
  {
    "type": "LineString",
    "properties": {
      "prop0": "value0",
      "prop1": 0
    },
    "arcs": [0]
  },
  {
    "type": "Polygon",
    "properties": {
      "prop0": "value0",
      "prop1": {
        "this": "that"
      }
    },
    "arcs": [[-2]]
  }
```

I think the test should try to extract these values from the OCaml value and check some of them for example that the first element is indeed a point and it contains the coordinates `[102, 0.5]`.

**Comment by olybeke** [comment]
Hi mentor @patricoferris, I'm Oluchi Nwankwo, an outreachy applicant. I would like to work on this issue. can you assign it to me?

**Comment by patricoferris** [comment]
Hey @olybeke, have got your OCaml development environment all configured? If so, then sure :))

**Comment by olybeke** [comment]
Yes, I have

**Comment by patricoferris** [comment]
Great!

**Comment by Priceless-P** [comment]
Hi @patricoferris, please I'd like to fix this issue.

**Comment by patricoferris** [comment]
Awesome, let me know if you need help :))

**Comment by Priceless-P** [comment]
Okay, sure

**Comment by patricoferris** [comment]
We have a bunch of tests which cover all of this I think
