### ISSUE TITLE
Geometry objects can contain `"id"` fields

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-topojson#4]
The TopoJSON spec mentions an `"id"` field, similarly to GeoJSON which should be handled by this library:

> If a geometry has a commonly used identifier, that identifier should be included as a member of the geometry object with the name “id”. 

(see https://github.com/topojson/topojson-specification#22-geometry-objects)

**Comment by mimi-tech** [comment]
Hi @patricoferris I am an outreachy applicant, Please can I work on this issue?

**Comment by patricoferris** [comment]
Hi @mimi-tech, thank you for wanting to contribute. 

Can I just double-check that you have the repository building locally? If you do then of course, otherwise it would be good to get that working first.

**Comment by mimi-tech** [comment]
@patricoferris Not yet, I need your approval to do the task then I will go ahead in setting the repo up. Meanwhile is this the repo I am to pull from https://github.com/geocaml/ocaml-topojson

**Comment by patricoferris** [comment]
It would be great to make sure you have the repository setup first if that's okay, then I can definitely assign you the issue (don't worry I can create another issue for you if this one has gone by then). There tends to be quite a lot of applicants from Outreachy and this makes it a bit fairer to those who are already setup and ready to contribute.

There are some instructions here: https://github.com/geocaml/ocaml-topojson/blob/main/CONTRIBUTING.md -- please do ask questions if you are stuck (I'm on discord, discuss with the same username)

**Comment by mimi-tech** [comment]
@patricoferris Thanks a lot, I am doing the installation right away

**Comment by mimi-tech** [comment]
@patricoferris I have successfully done the setup and cloned the repo, I have installed all dependencies by running this command opam install . --deps-only --with-test and also dune build and dune runtest. Everything went successfully. Please how do I start fixing the bug. Thank you.

**Comment by patricoferris** [comment]
Great thanks for doing that. The geometry objects we have in this library should be able to hand `id` fields as per the TopoJSON spec. 

https://github.com/geocaml/ocaml-topojson/blob/c9e7bcd57e0126edf340f63c535d758d7a0c707a/src/topojson/topojson.ml#L247-L250

I think we need to add them and the relevant encoding and decoding logic too.

**Comment by mimi-tech** [comment]
Hi @patricoferris Please do you mean I should pass the id field as this 
and t = { 
   geometry : geometry; 
   properties : properties; 
   foreign_members : (string * json) list; 
   id:id;

**Comment by patricoferris** [comment]
That seems reasonable to me 👍

**Comment by mimi-tech** [comment]
@patricoferris Alright I will be doing that right away and I will make a PR. Thanks
