### ISSUE TITLE
MDX Docs: Add example of reading a raw JSON string

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-topojson#7]
Currently we only have an example of reading an OCaml value that represents JSON (see https://github.com/geocaml/ocaml-topojson#reading). It would be good to provide an example where we read a JSON string i.e. `{ "type": "Topology"...` which is more likely what users will do.

**Comment by EngOmbasa** [comment]
Hello @patricoferris , I am  Joshua, an Outreachy applicant and would like to work on this issue. I have already set up OCaml and its package manager opam and I really look forward to your approval to start contributing to this effort.

**Comment by patricoferris** [comment]
Great, thank you for wanting to contribute and for setting everything up, I've assigned you the issue :))

**Comment by patricoferris** [comment]
@EngOmbasa how's everything going, anything you need help with ?

**Comment by EngOmbasa** [comment]
Hi @patricoferris ! Having had no experience in OCaml, the learning curve is so steep. It was hard to know where best to start, but I solved this by jumping in at the basics. I have learned more about the purpose of geocaml tools and libraries, and taught myself more about coding in Ocaml and functional programming in general. Soon enough, I will be comfortable to jump into the codebase and play around with the issues you assigned me, learning more as I go.

**Comment by EngOmbasa** [comment]
Hi @patricoferris !
I thought of this:
**For simple JSON string**

```
_utop # (*In this example I have used a simple JSON string *)_

let json_string = {|
{"name" : "Joshua Ombasa",
"age" : 25,
"country" : "Kenya",
"passion" : ["basketball","chess","charity"]}|};;


utop # #require "yojson";;

utop # let json = Yojson.Safe.from_string json_string;;

utop # Format.printf "Parsed to %a" Yojson.Safe.pp json;;
```

**For a topojson string:**

```
_utop # (*In this example I have used a simple topoJSON string *)_

utop # let topojson_string = {|{
    "arcs": [[[0.0, 0.0], [0.0, 9999.0], [2000.0, 0.0], [0.0, -9999.0], [-2000.0, 0.0]]],
    "objects": {"example ": {
            "type": "GeometryCollection",
            "geometries": [
                {"coordinates": [4000.0, 5000.0],
                 "properties": {"prop0": "value0"},
                 "type": "Point"},
                {"arcs": [[0]],
                 "properties": {"prop0": "value0", "prop1": {"this": "that"}},
                 "type": "Polygon"}
            ]
     }},
    "transform": {"scale": [0.0005, 0.0001], "translate": [100.0, 0.0]},
    "type": "Topology"
}|};;

utop # #require "yojson";;

utop # open Yojson;;

let json = Yojson.Safe.from_string topojson_string;;

utop # Format.printf "Parsed to %a" Yojson.Safe.pp json;;
```

**Comment by EngOmbasa** [comment]
@patricoferris  Kindly advice.

**Comment by patricoferris** [comment]
Hey @EngOmbasa,

Thanks! I formatted your comment to use [codeblock](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) so it is easier to read.

I don't think we need the "Reading a JSON string" example (also it's completely up to you, but in examples is best to use made up information rather than personal information, but as I said that's up to you ^^).

Yes! Your TopoJSON example looks good to me. However two points:

1. We want to read the raw JSON string into the TopoJSON library. At the moment you have gone as far as JSON to OCaml, we need the last step of OCaml to `Topojson.t`. I.e. using
https://github.com/geocaml/ocaml-topojson/blob/5bc10d52c1102e5a4a666848e17d45768a70669d/src/topojson/topojson_intf.ml#L226

3. Yojson is a perfectly good choice, but we're already using `Ezjsonm` (see [here](https://github.com/geocaml/ocaml-topojson/blob/5bc10d52c1102e5a4a666848e17d45768a70669d/doc/prelude.txt#L3-L22)) for the examples so let's stick with that :)

**Comment by patricoferris** [comment]
Hi @EngOmbasa, how's everything going ? Can I help getting a PR over the line ?

**Comment by EngOmbasa** [comment]
Hi @patricoferris ! Almost there!

**Comment by EngOmbasa** [comment]
Hi @patricoferris ! I  tried this;
``` ocaml
#require "topojson";;
#require "ezjsonm";;
module Topojson = Topojson.Make (Ezjsonm_parser);;
let topojson_string = {|{
    "arcs": [[[0.0, 0.0], [0.0, 9999.0], [2000.0, 0.0], [0.0, -9999.0], [-2000.0, 0.0]]],
    "objects": {"example ": {
            "type": "GeometryCollection",
            "geometries": [
                {"coordinates": [4000.0, 5000.0],
                 "properties": {"prop0": "value0"},
                 "type": "Point"},
                {"arcs": [[0]],
                 "properties": {"prop0": "value0", "prop1": {"this": "that"}},
                 "type": "Polygon"}
            ]
     }},
    "transform": {"scale": [0.0005, 0.0001], "translate": [100.0, 0.0]},
    "type": "Topology"
}|};;
#Topojson.of_json topojson_string;;
```
However I am running into this error, 
```ocaml
Error: Unbound module Topojson

```
I have tried various ways of installing the package Topojson but none has worked. I have checked around the Ocaml community chat but I cant get any help. Kindly advice.

**Comment by patricoferris** [comment]
If you just add this to the README.md as a code block e.g. 

```ocaml
# let topojson_string = {|{
    "arcs": [[[0.0, 0.0], [0.0, 9999.0], [2000.0, 0.0], [0.0, -9999.0], [-2000.0, 0.0]]],
    "objects": {"example ": {
            "type": "GeometryCollection",
            "geometries": [
                {"coordinates": [4000.0, 5000.0],
                 "properties": {"prop0": "value0"},
                 "type": "Point"},
                {"arcs": [[0]],
                 "properties": {"prop0": "value0", "prop1": {"this": "that"}},
                 "type": "Polygon"}
            ]
     }},
    "transform": {"scale": [0.0005, 0.0001], "translate": [100.0, 0.0]},
    "type": "Topology"
}|};;
```

And run a combination of `dune runtest` and then `dune promote` -- this will be easier I think as it already has topojson available. Feel free to then push that code which will make it a lot easier to help and debug.

**Comment by EngOmbasa** [comment]
Hi @patricoferris ! I will try that. Thank you for the quick response.

**Comment by EngOmbasa** [comment]
Hi @patricoferris.  Does #23 and #26 fix this issue fully?

**Comment by patricoferris** [comment]
Yep, thanks
