### ISSUE TITLE
MDX Docs: Provide an example of building a TopoJSON object and writing it to a string

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-topojson#8]
This requires:

 - Providing a constructor function for making [values of type `t`](https://github.com/geocaml/ocaml-topojson/blob/15b98302c424746a6709a3b948aad9fc765d6b48/src/topojson/topojson_intf.ml#L215)
 - Then building a TopoJSON object
 - Serialise the object to JSON

**Comment by OmkarAcharekar** [comment]
Hi @patricoferris , My name is Omkar Acharekar, I am an Outreachy applicant .  I got intermediate experience with Ocaml. I had setup the working enviornment  and  want to work on this issue. Thanks

**Comment by OmkarAcharekar** [comment]
Hi @patricoferris , Sir My name is Omkar Acharekar( Outreachy applicant ).  I got little experience with Ocaml. I had setup the working enviornment and want to work on this issue. Thanks

**Comment by patricoferris** [comment]
Great to have you here @OmkarAcharekar, I've assigned you the issue.

**Comment by patricoferris** [comment]
Fixed in #33
