### ISSUE TITLE
MDX Docs: Example usage of `foreign_members`

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-topojson#9]
Use the function [`foreign_members`](https://github.com/geocaml/ocaml-topojson/blob/15b98302c424746a6709a3b948aad9fc765d6b48/src/topojson/topojson_intf.ml#L184) to read some key-value pairs that are not a part of the specification.

**Comment by mahamtariq58** [comment]
Hi @patricoferris, I would like to try this issue.

- [x] Setup the OCaml development environment
- [x] Cloned the OCaml-topojson repository
- [x] Installed the dependencies and run the tests


![ocaml](https://user-images.githubusercontent.com/11984160/195263449-ba56fb7d-5837-4ba8-a38c-ee9530a1b0f2.png)

Guide me if I am doing anything wrong or missing any step. Thank you

**Comment by patricoferris** [comment]
Excellent, thank you for setting everything up before working on the issue. I just assigned you it :))

**Comment by mahamtariq58** [comment]
Thank you ....get back to you soon!

**Comment by mahamtariq58** [comment]
Hello, mentor @patricoferris ... I was going through the different resources as I am new to Ocaml and mdx docs... Can you please elaborate and point me to resources relevant to this issue, Big Thanks!

**Comment by patricoferris** [comment]
The best place to start would be the MDX documentation: https://github.com/realworldocaml/mdx

The setup here has already been done so it's a matter of learning how to use markdown codeblocks to make examples.

**Comment by patricoferris** [comment]
Hi @mahamtariq58, how's this issue going? Are you still working on it ? Any way I can help :)) ?

**Comment by patricoferris** [comment]
Fixed in #35
